# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Park.create(name: "Yellowstone", state: "Wyoming", photo: "https://i.imgur.com/XMle8nq.jpg", description: "On March 1, 1872, Yellowstone became the first national park for all to enjoy the unique hydrothermal and geologic wonders. Today, the park hosts millions of visitors annually, from winter visitors exploring wintery snowscapes to summer visitors observing wildlife in an intact ecosystem and watching those same hydrothermal wonders. What are some of your favorite Yellowstone memories?")
Park.create(name: "Denali", state: "Alaska", photo: "https://i.imgur.com/jiusmEy.jpg", description: "Denali is six million acres of wild land, bisected by one ribbon of road. Travelers along it see the relatively low-elevation taiga forest give way to high alpine tundra and snowy mountains, culminating in North America's tallest peak, 20,310' Denali. Wild animals large and small roam unfenced lands, living as they have for ages. Solitude, tranquility and wilderness await.")
Park.create(name: "Yosemite", state: "California", photo: "https://images.unsplash.com/photo-1498429089284-41f8cf3ffd39?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80", description: "Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra.
First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.")
Park.create(name: "Grand Canyon", state: "Arizona", photo: "https://images.unsplash.com/photo-1527333656061-ca7adf608ae1?ixlib=rb-1.2.1&w=1000&q=80", description: "Unique combinations of geologic color and erosional forms decorate a canyon that is 277 river miles (446km) long, up to 18 miles (29km) wide, and a mile (1.6km) deep. Grand Canyon overwhelms our senses through its immense size.")
Park.create(name: "Badlands", state: "South Dakota", photo: "https://images.squarespace-cdn.com/content/v1/564d14dfe4b0290681184a82/1486336414522-YTQSGN9OL3ABODS42BRH/ke17ZwdGBToddI8pDm48kKAwwdAfKsTlKsCcElEApLR7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1UegTYNQkRo-Jk4EWsyBNhwKrKLo5CceA1-Tdpfgyxoog5ck0MD3_q0rY3jFJjjoLbQ/Badlands+National+Park+-+030.jpg", description: "The rugged beauty of the Badlands draws visitors from around the world. These striking geologic deposits contain one of the world’s richest fossil beds. Ancient mammals such as the rhino, horse, and saber-toothed cat once roamed here. The park’s 244,000 acres protect an expanse of mixed-grass prairie where bison, bighorn sheep, prairie dogs, and black-footed ferrets live today.")
